#!/usr/bin/env bash
set -e

_sub_cmd1(){
    _USAGE="cmd1"
    _HELP="cmd1 is an awesome command"

    run(){
        echo run cmd1
    }
}

_sub_cmd2(){
    _USAGE="cmd2"
    _HELP="cmd2 is an more awesome command"

    run(){
        echo run cmd2
    }
}


# -----

_sub_help(){
    _USAGE="help"
    _HELP="display help"

    run(){
        cmd "$1" && echo $0 $1 : $_HELP
    }
    _list(){
        fns=$(declare -F | sed -n 's/declare -f _sub_//p')
        for fn in $fns; do
            cmd "$fn" && printf "%s : %s\n" "$_USAGE" "$_HELP"
        done
    }
}

die(){ echo $@; exit 1;}
cmd(){ cmd="_sub_$1"; declare -f "$cmd" > /dev/null && "$cmd" || die $1 unknown;  }

_main(){
    command="$1"
    case "$command" in
    "" | "-h" | "--help" )
      cmd "help" && _list
      ;;
    * )
      cmd "$1" && { shift; run "$@"; }
      ;;
    esac
}
_main $@
